# Generated by Django 6.0.7 on 2026-09-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('timezone', models.CharField(max_length=64)),
                ('address1', models.CharField(max_length=512)),
                ('address2', models.CharField(max_length=512, null=True)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('trim_level', models.CharField(max_length=8)),
                ('vin_number', models.CharField(max_length=17)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=9)),
                ('street_datetime', models.DateTimeField()),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='playground.dealership')),
            ],
        ),
    ]
